module.exports = [
  'Fernando Pessoa',
  'William Shakespeare',
  'Desconhecido',
  'Clarice Lispector',
  'Maria Julia Paes de Silva',
  'Friedrich Nietzsche',
  'Augusto Cury',
  'Mario Quintana',
  'Pitagoras',
  'Confucio',
  'Haile Selassie',
  'Carlos Drummond de Andrade',
  'Dalai Lama',
  'Machado de Assis',
  'Roberto Shinyashiki',
  'Aristoteles',
  'Oscar Wilde',
  'Charles Chaplin',
  'Albert Einstein',
  'John Wooden',
  'D Elhers',
  'Fernando Teixeira de Andrade',
  'Gloria Hurtado',
  'Thich Nhat Hanh',
  'Paulo Coelho',
  'Platao',
  'Leonardo da Vinci',
  'Evelyn Beatrice Hall',
  'Geraldo Eustaquio de Souza',
  'Roger Bussy-Rabutin',
  'Joseph Addison',
  'Toquinho e Mutinho',
  'Myrtes Mathias',
  'Georges Bernanos',
  'Lilian Tonet',
  'Socrates',
  'Nemo Nox',
  'Amyr Klink',
  'Cora Coralina',
  'Garth Henrichs',
  'Vinicius de Moraes',
  'Buda',
  'Sarah Westphal',
  'Paulo Roberto Gaefke',
  'Seneca',
  'Santo Agostinho',
  'Millor Fernandes',
  'Martin Luther King',
  'Vladimir Maiakovski',
  'John Dryden',
  'Oliver Goldsmith',
  'Oswaldo Montenegro',
  'Maurice Switzer',
  'Waldemar Valle Martins',
  'Leon Tolstoi',
  'Jo Cooke',
  'Mahatma Gandhi',
  'Voltaire',
  'Henry Ford',
  'Sigmund Freud',
  'Benjamin Franklin',
  'Khalil Gibran',
  'Rui Barbosa',
  'Will Durant',
  'Soren Kierkegaard',
  'Elbert Hubbard',
  'Dinamor'
];
